# Generated by Django 4.2.5 on 2023-09-28 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='vehicle_rent_factory_outside_rate',
            new_name='vehicle_rent_factory_rate',
        ),
    ]
