# Generated by Django 4.2.5 on 2023-09-26 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=45)),
                ('product_charge', models.DecimalField(
                    decimal_places=3, max_digits=15, null=True)),
                ('vehicle_rent', models.DecimalField(
                    decimal_places=3, max_digits=15, null=True)),
                ('wrapping', models.CharField(max_length=45, null=True)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(db_column='created_by',
                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.ForeignKey(db_column='updated+by', null=True,
                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'salegroup',
            },
        ),
    ]
